### PR TITLE
Big Bomb!

### PR DESCRIPTION
**Pull request by laobubu**
## Major

* [x] New structure / skeleton for addons
  * New structure is much more clear and will make the doc generator possible!
  * [x] Refractored all old addons
* [x] **Bundler First**! Plain Browser Env or RequireJS is not as important as before.
* [x] **CSS files are imported via JavaScript**
  * [x] Make a patch for RequireJS
* [x] Use **PowerPack** to load all **3rd-party libs**
  * HyperMD will NOT directly depend on any 3rd-party libs except "codemirror"! If you want to use one, install it and use it via *PowerPack*s
  * [x] MathJax
  * [x] KaTeX
  * [x] marked
  * [x] Turndown
* [x] New Building Scripts
  * Use TypeScript to compile, which is faster.
  * Fix tsc's bad UMD style after compiling.
* [x] Document Generator? *(maybe not necessary)

## Minor

* [x] Custom table column alignments
* [x] Better KeyMap for tables
* [x] Better KeyMap for lists
* [x] More CodeMirror builtin goods
  * closebrackets

### CODE REVIEW

**Comment by nokola** [comment]
This is a great change, congratulations!

**Comment by laobubu** [comment]
Made a documentation generator! Here is the output:

https://raw.githubusercontent.com/laobubu/HyperMD/dfd57eb61b715b32b3fce229006631320fb92210/docs/configurations.md

**Comment by laobubu** [comment]
Whoops, TypeScript 2.9.1 changed a lot. The doc-making script can't get the correct type declarations 😢

**Comment by laobubu** [comment]
http://laobubu.net/HyperMD/?directOpen#./docs/configurations.md

The generated document looks good. But the links to source code is still inaccurate. Anyway it works now.

**Pull request merged**
